### ISSUE TITLE
Emacs setup instructions

### ISSUE THREAD

**Issue by ahonnecke** [charliermarsh/ruff-lsp#45] opened 2022-12-28 20:53 UTC
Trying to figure out what to do after `pip install ruff-lsp` to get this working in emacs.  I came across https://github.com/emacs-lsp/lsp-mode/issues/3876 which seems to indicate that there's more to do to get it up and running.  Happy to help test steps.

**Comment by charliermarsh** [comment] 2022-12-28 22:00
I think @rassie has figured this out (https://github.com/charliermarsh/ruff-lsp/issues/43) but we don't have docs yet. Maybe they can share some insights?

(Gonna mark as a duplicate of https://github.com/charliermarsh/ruff-lsp/issues/19 for now though.)

**Closed by charliermarsh** 2022-12-28 22:00 UTC
